package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class Esce1Controller {
	@FXML
	private Button button1;
	@FXML
	private Button button2;

	// Event Listener on Button[#button1].onAction
	@FXML
	public void introducir(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#button2].onAction
	@FXML
	public void consultar(ActionEvent event) {
		// TODO Autogenerated
	}
}
