package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

public class Esce1Controller {
	@FXML
	private Button button1;
	@FXML
	private TextField usuario;

	// Event Listener on Button[#button1].onAction
	@FXML
	public void ingresar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox.onAction
	@FXML
	public void select(ActionEvent event) {
		// TODO Autogenerated
	}
	

	public void initialize() {
		ComboBox comboBox = new ComboBox();
		comboBox.setItems(FXCollections.observableArrayList("Ingresar Empleado", "Consultar Empleados"));
		
		

		
	}
	
}
